---
# --> (Example) Create an IngressRoute for your service...
 apiVersion: traefik.io/v1alpha1
 kind: IngressRoute
 metadata:
   name: nerdy-k8s-volume-manager-dev-ingressroute  # <-- Replace with your IngressRoute name
   namespace: nerdy-k8s-volume-manager-dev  # <-- Replace with your namespace
 spec:
   entryPoints:
     - web
     - websecure
   routes:
     - match: Host(`nkvm-dev.lib-nauto-apps.lab.aheadaviation.com`)  # <-- Replace with your FQDN
       kind: Rule
       services:
         - name: nerdy-k8s-volume-manager  # <-- Replace with your service name
           port: 80
# --> (Optional) Add certificate secret
# tls:
#     secretName: your-certificate-secret
# <--
