dockerRegistry:
  enabled: false

ingress:
  enabled: false

redis:
  local_setup: true
  storageClass: "rook-cephfs-delete"
  volumeSize: 100Mi

postgres:
  local_setup: true
  storageClass: "rook-cephfs-retain"
  volumeSize: 1Gi

rabbitmq:
  local_setup: true
  storageClass: "rook-cephfs-delete"
  volumeSize: 100Mi
  default_user: plane
  default_password: plane

minio:
  local_setup: true
  root_password: password
  root_user: admin
  storageClass: "rook-cephfs-retain"
  volumeSize: 1Gi
  env:
    minio_endpoint_ssl: false


external_secrets:
  # Name of the existing Kubernetes Secret resource; see README for more details
  rabbitmq_existingSecret: ''
  pgdb_existingSecret: ''
  doc_store_existingSecret: ''
  app_env_existingSecret: ''
  live_env_existingSecret: ''

env:

  # NEXT_PUBLIC_DEPLOY_URL:  ""
  # REDIS
  remote_redis_url: "" #INCASE OF REMOTE REDIS ONLY

  # POSTGRES DB VALUES
  pgdb_username: plane
  pgdb_password: plane
  pgdb_name: plane
  pgdb_remote_url: "" #INCASE OF REMOTE PG DB URL ONLY

  # DATA STORE
  docstore_bucket: "uploads"
  doc_upload_size_limit: "5242880" # 5MB

  # REQUIRED IF MINIO LOCAL SETUP IS FALSE
  aws_access_key: ""
  aws_secret_access_key: ""
  aws_region: ""
  aws_s3_endpoint_url: ""

  secret_key: "60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5"
  live_server_secret_key: "htbqvBJAgpm9bzvf3r4urJer0ENReatceh"

  sentry_dsn: ""
  sentry_environment: ""

  cors_allowed_origins: ""
  default_cluster_domain: cluster.local

  api_key_rate_limit: "60/minute"
